name: Daily podcast

on:
  schedule:
    # 06:00 UTC = 07:00 BST (London summer time)
    - cron: "0 6 * * *"
  workflow_dispatch:      # lets you test it manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install deps
      run: pip install openai feedparser python-dateutil lxml requests

- name: 🔍 check key length
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  run: |
    echo "KEYLEN=${#OPENAI_API_KEY}"


    - name: Generate episode
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python .github/scripts/generate_episode.py

    - name: Commit & push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add feed.xml episodes/*.mp3
        git commit -m "feat: add episode $(date -u +'%Y-%m-%d')" || echo "Nothing to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
